#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DEVICE_DIR="$PROJECT_ROOT/device"
REGISTRY="$DEVICE_DIR/registry.json"
FIRMWARE="$PROJECT_ROOT/bin/ESP32_GENERIC-20251209-v1.27.0.bin"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

usage() {
    echo "Usage: $0 <device-id> [options]"
    echo ""
    echo "Arguments:"
    echo "  device-id       Device ID from registry.json (e.g., esp32-1, esp32-2)"
    echo ""
    echo "Options:"
    echo "  --port, -p      Serial port (auto-detected if not specified)"
    echo "  --erase         Erase flash and install MicroPython firmware"
    echo "  --list          List available devices in registry"
    echo "  --help, -h      Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 esp32-1                    # Flash esp32-1 with auto-detected port"
    echo "  $0 esp32-2 -p /dev/ttyUSB0    # Flash esp32-2 on specific port"
    echo "  $0 esp32-1 --erase            # Full flash including MicroPython"
    echo "  $0 --list                     # Show registered devices"
    exit 1
}

list_devices() {
    echo -e "${GREEN}Registered devices:${NC}"
    jq -r '.devices | to_entries[] | "  \(.key): \(.value.location)"' "$REGISTRY"
    exit 0
}

detect_port() {
    # Try common serial port patterns
    local ports=()

    # macOS
    for p in /dev/tty.usbserial-* /dev/tty.usbmodem* /dev/tty.SLAB_USBtoUART*; do
        [[ -e "$p" ]] && ports+=("$p")
    done

    # Linux
    for p in /dev/ttyUSB* /dev/ttyACM*; do
        [[ -e "$p" ]] && ports+=("$p")
    done

    if [[ ${#ports[@]} -eq 0 ]]; then
        echo -e "${RED}Error: No USB serial device found${NC}" >&2
        exit 1
    elif [[ ${#ports[@]} -gt 1 ]]; then
        echo -e "${YELLOW}Multiple serial devices found:${NC}" >&2
        printf '  %s\n' "${ports[@]}" >&2
        echo -e "${YELLOW}Please specify with --port${NC}" >&2
        exit 1
    fi

    echo "${ports[0]}"
}

generate_secrets() {
    local device_id="$1"
    local output="$DEVICE_DIR/secrets.py"

    # Extract device config
    local location=$(jq -r ".devices[\"$device_id\"].location" "$REGISTRY")
    local sensor_pin=$(jq -r ".devices[\"$device_id\"].sensor_pin" "$REGISTRY")
    local sensor_type=$(jq -r ".devices[\"$device_id\"].sensor_type" "$REGISTRY")
    local led_pin=$(jq -r ".devices[\"$device_id\"].led_pin" "$REGISTRY")

    # Extract defaults
    local mqtt_host=$(jq -r ".defaults.mqtt_host" "$REGISTRY")
    local mqtt_port=$(jq -r ".defaults.mqtt_port" "$REGISTRY")
    local wifi_ssid=$(jq -r ".defaults.wifi_ssid" "$REGISTRY")
    local wifi_password=$(jq -r ".defaults.wifi_password" "$REGISTRY")

    cat > "$output" << EOF
# Auto-generated by flash.sh for device: $device_id
# Do not edit manually - update registry.json instead

SSID = "$wifi_ssid"
PASSWORD = "$wifi_password"

MQTT_HOST = "$mqtt_host"
MQTT_PORT = $mqtt_port
MQTT_CLIENT_ID = "$device_id"
DEVICE_LOCATION = "$location"

# Hardware config
SENSOR_PIN = $sensor_pin
SENSOR_TYPE = "$sensor_type"
LED_PIN = $led_pin
EOF

    echo -e "${GREEN}Generated secrets.py for $device_id${NC}"
}

flash_firmware() {
    local port="$1"

    echo -e "${YELLOW}Erasing flash...${NC}"
    esptool --port "$port" erase-flash

    echo -e "${YELLOW}Flashing MicroPython firmware...${NC}"
    esptool --port "$port" --baud 460800 write-flash -z 0x1000 "$FIRMWARE"

    echo -e "${GREEN}Firmware flashed successfully${NC}"
    sleep 2
}

upload_files() {
    local port="$1"

    echo -e "${YELLOW}Uploading device files...${NC}"

    # Upload directories
    mpremote connect "$port" fs cp -r "$DEVICE_DIR/lib" :
    mpremote connect "$port" fs cp -r "$DEVICE_DIR/services" :

    # Upload main files
    mpremote connect "$port" fs cp "$DEVICE_DIR/boot.py" :
    mpremote connect "$port" fs cp "$DEVICE_DIR/main.py" :
    mpremote connect "$port" fs cp "$DEVICE_DIR/config.py" :
    mpremote connect "$port" fs cp "$DEVICE_DIR/secrets.py" :

    echo -e "${GREEN}Files uploaded successfully${NC}"
}

verify_device() {
    local port="$1"
    local device_id="$2"

    echo -e "${YELLOW}Verifying installation...${NC}"

    # Check MicroPython is running
    local version=$(mpremote connect "$port" exec "import sys; print(sys.implementation.version)" 2>/dev/null)
    if [[ -z "$version" ]]; then
        echo -e "${RED}Error: MicroPython not responding${NC}"
        return 1
    fi
    echo -e "  MicroPython: ${GREEN}$version${NC}"

    # Check secrets loaded correctly
    local loaded_id=$(mpremote connect "$port" exec "from secrets import MQTT_CLIENT_ID; print(MQTT_CLIENT_ID)" 2>/dev/null)
    if [[ "$loaded_id" != "$device_id" ]]; then
        echo -e "${RED}Error: Device ID mismatch (expected $device_id, got $loaded_id)${NC}"
        return 1
    fi
    echo -e "  Device ID: ${GREEN}$loaded_id${NC}"

    echo -e "${GREEN}Verification passed${NC}"
}

# Parse arguments
DEVICE_ID=""
PORT=""
ERASE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --list)
            list_devices
            ;;
        --port|-p)
            PORT="$2"
            shift 2
            ;;
        --erase)
            ERASE=true
            shift
            ;;
        --help|-h)
            usage
            ;;
        -*)
            echo -e "${RED}Unknown option: $1${NC}"
            usage
            ;;
        *)
            DEVICE_ID="$1"
            shift
            ;;
    esac
done

# Validate device ID
if [[ -z "$DEVICE_ID" ]]; then
    echo -e "${RED}Error: Device ID required${NC}"
    usage
fi

# Check registry exists
if [[ ! -f "$REGISTRY" ]]; then
    echo -e "${RED}Error: Registry not found at $REGISTRY${NC}"
    exit 1
fi

# Check device exists in registry
if ! jq -e ".devices[\"$DEVICE_ID\"]" "$REGISTRY" > /dev/null 2>&1; then
    echo -e "${RED}Error: Device '$DEVICE_ID' not found in registry${NC}"
    echo "Available devices:"
    jq -r '.devices | keys[]' "$REGISTRY" | sed 's/^/  /'
    exit 1
fi

# Auto-detect port if not specified
if [[ -z "$PORT" ]]; then
    PORT=$(detect_port)
fi

echo -e "${GREEN}Flashing device: $DEVICE_ID${NC}"
echo -e "  Port: $PORT"
echo ""

# Generate secrets.py
generate_secrets "$DEVICE_ID"

# Flash firmware if requested
if $ERASE; then
    flash_firmware "$PORT"
fi

# Upload files
upload_files "$PORT"

# Reset and verify
echo -e "${YELLOW}Resetting device...${NC}"
mpremote connect "$PORT" soft-reset
sleep 3

verify_device "$PORT" "$DEVICE_ID"

echo ""
echo -e "${GREEN}Done! Device $DEVICE_ID is ready.${NC}"
echo -e "Use ${YELLOW}./tools/repl.sh${NC} to monitor output."
